name: Deployment

on: 
    push: 
        branches: 
            - chore/repo_setup 


jobs: 
    deploy: 
        runs-on: ubuntu-latest 
        steps: 
            - name: Trigger Deployment
              run: | 
                curl -X POST "${{secrets.RENDER_DEPLOY_HOOK}}"